version: '3.9'

networks:
  hookio: {}

volumes:
  postgres_data: {}
  dragonfly_data: {}

services:
  # Main database
  postgres:
    image: postgres:16.2
    networks:
      - hookio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.postgres
    ports:
      - 5432
  
  # Ratelimit and cache
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    networks:
      - hookio
    volumes:
      - dragonfly_data:/data
    # add custom redis.conf
    ports:
      - 6379
  
  # Website (nginx)
  client:
    build: client
    networks:
      - hookio
    depends_on:
      - postgres
      - dragonfly
      - server
    ports:
      - 80:80
      - 443:443
    env_file:
      - client/.env.production
  
  # Server (ASP.NET)
  server:
    build: server
    networks:
      - hookio
    depends_on:
      - postgres
      - dragonfly
    environment:
      - ASPNETCORE_URLS=http://+:7109
    ports:
      - 7109
    env_file:
      - server/Hookio/.env.production