version: '3.9'

networks:
  hookio: {}

volumes:
  postgres_data: {}
  redis_data: {}

services:
  # Main database
  postgres:
    image: postgres:16.1
    networks:
      - hookio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.postgres
    ports:
      - 5432
  
  # Ratelimit and cache
  redis:
    image: redis:7.2.4
    networks:
      - hookio
    volumes:
      - redis_data:/data
    # add custom redis.conf
    ports:
      - 6379
  
  # Website (nginx)
  client:
    build: client
    networks:
      - hookio
    depends_on:
      - postgres
      - redis
      - server
    ports:
      - 80:80
      - 443:443
    env_file:
      - client/.env
  
  # Server (ASP.NET)
  server:
    build: server
    networks:
      - hookio
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_URLS=http://+:7109
    ports:
      - 7109
    env_file:
      - server/.env