<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6d6a6b25-1298-4afc-92f0-9d36f28d5b28</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net.Rest" Version="3.16.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hookio.Contracts\Hookio.Contracts.csproj" />
    <ProjectReference Include="..\Hookio.DataManagers\Hookio.DataManagers.csproj" />
    <ProjectReference Include="..\Hookio.Shared\Hookio.Shared.csproj" />
    <ProjectReference Include="..\Hookio.YouTube\Hookio.YouTube.csproj" />
  </ItemGroup>

</Project>
